# Generated by Django 4.2.9 on 2024-01-17 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SongWriter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('rank', models.IntegerField()),
                ('year_released', models.IntegerField()),
                ('song_time', models.CharField(max_length=10)),
                ('spotify_streams', models.IntegerField()),
                ('rolling_stone_ranking', models.IntegerField()),
                ('nme_ranking', models.IntegerField(blank=True, null=True)),
                ('ug_views', models.IntegerField()),
                ('ug_favourites', models.IntegerField()),
                ('lyrics', models.JSONField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beatles.album')),
                ('singers', models.ManyToManyField(to='beatles.singer')),
                ('writers', models.ManyToManyField(to='beatles.songwriter')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='beatles_son_name_abe40e_idx'), models.Index(fields=['id'], name='beatles_son_id_0c7621_idx'), models.Index(fields=['rank'], name='beatles_son_rank_b0ab9d_idx'), models.Index(fields=['year_released'], name='beatles_son_year_re_0ea933_idx')],
            },
        ),
    ]
